### ISSUE TITLE
Error: Missing "./macros" specifier in "vue" package

### ISSUE THREAD

**Issue by amir20** [unplugin/unplugin-auto-import#512]
### Describe the bug

I was going a little crazy trying to investigate the following error: 

```
error when starting dev server:
Error: Missing "./macros" specifier in "vue" package
    at e (file:///Users/araminfar/Workspace/dozzle/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46568:25)
    at n (file:///Users/araminfar/Workspace/dozzle/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46568:627)
    at o (file:///Users/araminfar/Workspace/dozzle/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46568:1297)
    at resolveExportsOrImports (file:///Users/araminfar/Workspace/dozzle/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:47189:18)
    at resolveDeepImport (file:///Users/araminfar/Workspace/dozzle/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:47212:25)
    at tryNodeResolve (file:///Users/araminfar/Workspace/dozzle/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46977:16)
    at ResolveIdContext.resolveId (file:///Users/araminfar/Workspace/dozzle/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46727:19)
    at PluginContainer.resolveId (file:///Users/araminfar/Workspace/dozzle/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:49506:17)
    at async file:///Users/araminfar/Workspace/dozzle/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66561:15
    at async file:///Users/araminfar/Workspace/dozzle/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:50411:14
 ELIFECYCLE  Command failed with exit code 1.
```

After downgrading from `0.18` --> `0.17.6`, it started working again. 

I am trying to go through the changelog to see what could have caused this. 

### Reproduction

Still trying to figure out what is different with my project that is causing this

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M3 Pro
    Memory: 94.98 MB / 18.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.4.1 - ~/.local/state/fnm_multishells/36228_1721056518990/bin/node
    npm: 10.8.1 - ~/.local/state/fnm_multishells/36228_1721056518990/bin/npm
    pnpm: 9.5.0 - ~/.local/state/fnm_multishells/36228_1721056518990/bin/pnpm
    bun: 1.1.18 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by amir20** [comment]
Removing `vue/macros`, from AutoImport seems to fix the problem. Not sure if this is to be expected?

**Comment by antfu** [comment]
I guess you can remove `vue/macros` as it should no longer needed. Otherwise you can set `viteOptimizeDeps` to `false`
